name: build java_azulprime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  actions: read
  packages: write

jobs:
  build_and_push:
    name: "java${{ matrix.tag }}_azulprime"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 17
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
          

      - name: Login to registry Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to registry docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./java-azulprime/${{ matrix.tag }}
          file: ./java-azulprime/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lefraudeur/ptero_images:java${{ matrix.tag }}_azulprime
            lefraudeur/ptero_images:java${{ matrix.tag }}_azulprime
